-- Shared, on-demand translations of an item's summary. Generated by re-running
-- the summarize step over the original transcript + metadata with the output
-- language enforced (NOT by translating the existing summary). One row per
-- (item, language); the original-language summary stays in `summary`.
CREATE TABLE IF NOT EXISTS item_translation (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id        INTEGER NOT NULL REFERENCES item(id) ON DELETE CASCADE,
  lang           TEXT NOT NULL,                 -- target language code (en, ja, …)
  status         TEXT NOT NULL DEFAULT 'queued', -- queued|processing|done|error
  model          TEXT NOT NULL DEFAULT '',
  prompt_version TEXT NOT NULL DEFAULT '',
  markdown       TEXT NOT NULL DEFAULT '',
  structured     TEXT NOT NULL DEFAULT '{}',
  error          TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE(item_id, lang)
);
CREATE INDEX IF NOT EXISTS ix_translation_item ON item_translation(item_id);
