-- Shared, on-demand infographic poster for an item. Generated by an image model
-- (Gemini 3 Pro Image / "Nano Banana Pro") from the existing structured summary.
-- NOT auto-generated during the pipeline (image generation is ~$0.13/image); a
-- signed-in user requests it on the item page and the result is shared with
-- everyone. The PNG/JPEG itself lives in R2 (key in image_key); this row tracks
-- generation status + cost. One row per item.
CREATE TABLE IF NOT EXISTS item_infographic (
  item_id    INTEGER PRIMARY KEY REFERENCES item(id) ON DELETE CASCADE,
  status     TEXT NOT NULL DEFAULT 'queued', -- queued|processing|done|error
  model      TEXT NOT NULL DEFAULT '',
  image_key  TEXT,                            -- R2 object key (served via /media/<key>)
  mime_type  TEXT NOT NULL DEFAULT 'image/png',
  total_tokens INTEGER NOT NULL DEFAULT 0,
  cost_usd   REAL NOT NULL DEFAULT 0,
  error      TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
